import { mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import type { DocumentFormat, DocumentGenerationPayload } from "@/app/types/DocumentGeneration";
import { DOCUMENT_GENERATION_SERVER_CONFIG } from "./config";

const escapeText = (value: string) =>
  value
    .replaceAll("\\", "\\\\")
    .replaceAll("(", "\\(")
    .replaceAll(")", "\\)")
    .replaceAll("\r", " ")
    .replaceAll("\n", " ");

const stringifyPayloadSummary = (payload: DocumentGenerationPayload) => {
  const selectedCount = Array.isArray(payload.selectedItems) ? payload.selectedItems.length : 0;
  const customCount = Array.isArray(payload.customItems) ? payload.customItems.length : 0;

  return [
    "Mock document generation",
    `Selected recommendations: ${selectedCount}`,
    `Custom recommendations: ${customCount}`,
    `General comment: ${payload.generalComment || "-"}`,
  ].join("\n");
};

const createMockPdf = (text: string) => {
  const lines = text.split("\n").map((line, index) => `BT /F1 12 Tf 50 ${760 - index * 20} Td (${escapeText(line)}) Tj ET`);
  const content = lines.join("\n");

  return `%PDF-1.4
1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj
3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj
4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj
5 0 obj << /Length ${content.length} >> stream
${content}
endstream endobj
trailer << /Root 1 0 R >>
%%EOF`;
};

const createMockDocxContent = (text: string) =>
  [
    "Temporary DOCX mock file.",
    "This file is generated by the polling pipeline placeholder and will be replaced by real DOCX generation.",
    "",
    text,
  ].join("\n");

export const getDocumentGenerationTmpDir = () =>
  path.join(tmpdir(), DOCUMENT_GENERATION_SERVER_CONFIG.tmpDirName);

export const generateMockDocumentFile = async ({
  jobId,
  format,
  payload,
}: {
  jobId: string;
  format: DocumentFormat;
  payload: DocumentGenerationPayload;
}) => {
  const tmpDir = getDocumentGenerationTmpDir();
  await mkdir(tmpDir, { recursive: true });

  const filePath = path.join(tmpDir, `${jobId}.${format}`);
  const summary = stringifyPayloadSummary(payload);
  const content = format === "pdf" ? createMockPdf(summary) : createMockDocxContent(summary);

  await writeFile(filePath, content);

  return filePath;
};