import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import "./globals.css";

import AuthButtonsServer from './components/AuthButtonsServer';
// import Header from "./components/Header";
import ConditionalHeader from './components/ConditionalHeader';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body>
                 <ConditionalHeader>
                    <header id="header" className="header-section">
                    <div className="header-container">
                        <Link href="/" className="footer-logo-link">
                            <Image src="/images/logo-white.png"
                                   alt="Клинические рекомендации Минздрава — логотип" width="101" height="43"
                                   loading="eager" />
                        </Link>
                        <nav aria-label="Главное меню" className="navigation">
                            <ul className="main-menu">
                                <li><Link href="/#about">О проекте</Link></li>
                                <li><Link href="/#pricing">Тарифы</Link></li>
                                <li><Link href="/#video">Видео-инструкция</Link></li>
                                <li><Link href="/#contact">Контакты</Link></li>
                            </ul>
                        </nav>
                        <div className="header-buttons">
                            <AuthButtonsServer variant="header" />
                            <Link href="/login" className="btn btn-demo">Демо</Link>
                            <button type="button" className="btn btn-logout-preview">Выйти</button>
                            <Link href="/preview/directory/search" className="btn btn-back-preview">←Назад</Link>
                        </div>
                        <div className="mobile-nav">
                            <button className="burger-btn" aria-label="Открыть меню">
                                <span className="burger-line"></span>
                                <span className="burger-line"></span>
                                <span className="burger-line"></span>
                            </button>

                            <div className="mobile-menu">
                                <nav aria-label="Мобильное меню">
                                    <ul className="mobile-menu-list">
                                        <li><Link href="/#about">О проекте</Link></li>
                                        <li><Link href="/#pricing">Тарифы</Link></li>
                                        <li><Link href="/#video">Видео-инструкция</Link></li>
                                        <li><Link href="/#contact">Контакты</Link>
                                        </li>
                                    </ul>
                                </nav>
                                <div className="mobile-buttons">
                                    <Link href="/login" className="btn btn-login btn-auth">Войти</Link>
                                </div>
                            </div>
                        </div>
                        <div className="overlay hidden"></div>
                    </div>
                </header>
                </ConditionalHeader>

                <main>{children}</main>
                <footer id="footer" className="footer">
                    <div className="footer-container">
                        <section className="footer-nav" aria-labelledby="footer-nav-heading">
                            <h2 id="footer-nav-heading" className="visually-hidden">Навигация</h2>
                            <Link href="/" className="footer-logo-link">
                                <Image
                                    src="/images/logo-white.png"
                                    alt="Клинические рекомендации Минздрава — логотип"
                                    width="101"
                                    height="43"
                                    loading="eager"
                                />
                            </Link>

                            <nav>
                                <ul className="footer-menu">
                                    <li><Link href="/#about">О проекте</Link></li>
                                    <li><Link href="/#pricing">Тарифы</Link></li>
                                </ul>
                            </nav>

                            <div className="footer-buttons">
                                <AuthButtonsServer variant="footer" />
                                <Link href="/login" className="btn btn-demo footer-btn-demo">Демо</Link>
                            </div>
                        </section>

                        <section className="footer-contacts" id="contact" aria-labelledby="footer-contacts-heading">
                            <h2 id="footer-contacts-heading" className="visually-hidden">Контакты</h2>
                            <ul className="footer-contact-list">
                                <li><strong>Email: </strong><Link href="mailto:info@easymed.pro">info@easymed.pro</Link></li>
                                <li><strong>Telegram: </strong><Link href="https://t.me/easymed_admin" target="_blank" rel="noopener noreferrer">@easymed_admin</Link></li>
                            </ul>
                            <hr />
                        </section>

                        <section className="footer-legal" aria-labelledby="footer-legal-heading">
                            <h2 id="footer-legal-heading" className="visually-hidden">Правовая информация</h2>
                            <div className="legal-link">
                                <a href="/policy.pdf" target="_blank" rel="noopener noreferrer">
                                    Политика конфиденциальности
                                </a>
                                <a href="/agreement.pdf" target="_blank" rel="noopener noreferrer">
                                    Пользовательское соглашение
                                </a>
                            </div>
                            <div className="copyright">© 2025 easymed.pro</div>
                            <div className="inn">
                                ИП Васильцов Давыд Юрьевич<br />
                                ОГРНИП 324784700301501<br />
                                ИНН 781304344630
                            </div>
                        </section>
                    </div>
                </footer>
            </body>
        </html>
    );
}
