const SHORT_CART_VISIT_MS = 5_000;
const UNIQUE_OPENING_WINDOW_MS_VALUE = 2 * 60 * 1_000;

type CartVisit = {
  visitId: string;
  recommendationKey: string;
  openedAt?: number;
  leftAt?: number;
};

type UserOpeningState = {
  current?: CartVisit;
  countedRecommendations: Set<string>;
  processedEventIds: Set<string>;
  blocking: boolean;
};

type TrackerStore = Map<string, UserOpeningState>;
type UniqueOpeningState = { openings: Map<string, number>; blocking: boolean };
type UniqueOpeningStore = Map<string, UniqueOpeningState>;

declare global {
  var automatedClinicalRecommendationBrowsingStore: TrackerStore | undefined;
  var clinicalRecommendationOpeningStore: UniqueOpeningStore | undefined;
}

const store = globalThis.automatedClinicalRecommendationBrowsingStore ?? new Map();
globalThis.automatedClinicalRecommendationBrowsingStore = store;
const uniqueOpeningStore = globalThis.clinicalRecommendationOpeningStore ?? new Map();
globalThis.clinicalRecommendationOpeningStore = uniqueOpeningStore;

export const SUSPICIOUS_CART_VISIT_MS = SHORT_CART_VISIT_MS;
export const UNIQUE_OPENING_WINDOW_MS = UNIQUE_OPENING_WINDOW_MS_VALUE;

/** Existing detector for frequent unique recommendation data requests. */
export function recordUniqueOpening(
  userId: string,
  recommendationKey: string,
  limit: number,
  now = Date.now(),
): { shouldBlock: boolean; thresholdReached: boolean } {
  const state = uniqueOpeningStore.get(userId) ?? {
    openings: new Map<string, number>(),
    blocking: false,
  };
  const cutoff = now - UNIQUE_OPENING_WINDOW_MS_VALUE;

  for (const [key, openedAt] of state.openings) {
    if (openedAt < cutoff) state.openings.delete(key);
  }

  state.openings.set(recommendationKey, now);
  uniqueOpeningStore.set(userId, state);

  if (state.blocking) return { shouldBlock: false, thresholdReached: true };
  if (state.openings.size < limit) {
    return { shouldBlock: false, thresholdReached: false };
  }

  state.blocking = true;
  return { shouldBlock: true, thresholdReached: true };
}

export function releaseFailedUniqueOpeningBlock(userId: string): void {
  const state = uniqueOpeningStore.get(userId);
  if (state) state.blocking = false;
}

const getState = (userId: string) => {
  const existing = store.get(userId);
  if (existing) return existing;

  const state: UserOpeningState = {
    countedRecommendations: new Set(),
    processedEventIds: new Set(),
    blocking: false,
  };
  store.set(userId, state);
  return state;
};

export function recordOpeningEvent(
  userId: string,
  event: {
    eventId: string;
    type: "selected" | "cart_opened" | "cart_left";
    visitId: string;
    recommendationKey?: string;
  },
  limit: number,
  now = Date.now(),
): { shouldBlock: boolean; thresholdReached: boolean } {
  const state = getState(userId);

  // An event generated by sendBeacon may also be retried with fetch. Applying
  // it once makes every endpoint operation idempotent.
  if (state.processedEventIds.has(event.eventId)) {
    return { shouldBlock: false, thresholdReached: state.blocking };
  }
  state.processedEventIds.add(event.eventId);

  if (event.type === "selected" && event.recommendationKey) {
    const previous = state.current;
    const isShortCompletedVisit =
      previous?.openedAt !== undefined &&
      previous.leftAt !== undefined &&
      previous.leftAt - previous.openedAt < SHORT_CART_VISIT_MS;
    const isNewRecommendation =
      previous !== undefined &&
      previous.recommendationKey !== event.recommendationKey &&
      !state.countedRecommendations.has(event.recommendationKey);

    if (isShortCompletedVisit && isNewRecommendation) {
      state.countedRecommendations.add(event.recommendationKey);
    }

    state.current = {
      visitId: event.visitId,
      recommendationKey: event.recommendationKey,
    };
  } else if (state.current?.visitId === event.visitId) {
    if (event.type === "cart_opened") {
      // Preserve the first timestamp through reloads. This prevents a quick
      // refresh from disguising a long visit as a new short visit.
      state.current.openedAt ??= now;
      state.current.leftAt = undefined;
    } else if (event.type === "cart_left" && state.current.openedAt !== undefined) {
      state.current.leftAt = now;
    }
  }

  if (state.blocking) {
    return { shouldBlock: false, thresholdReached: true };
  }
  if (state.countedRecommendations.size < limit) {
    return { shouldBlock: false, thresholdReached: false };
  }

  state.blocking = true;
  return { shouldBlock: true, thresholdReached: true };
}

export function releaseFailedAutomatedBrowsingBlock(userId: string): void {
  const state = store.get(userId);
  if (state) state.blocking = false;
}